from __future__ import annotations
from sqlalchemy import Column, Integer, String, BigInteger, Boolean, DateTime, Date, Numeric, ForeignKey
from app.core.database import MssqlReadBase


class RecruitCandidateMst(MssqlReadBase):
    __tablename__ = "RecruitCandidateMst"
    __table_args__ = {"schema": "dbo"}

    CandidateID = Column(BigInteger, primary_key=True)
    CandidateApplicationDate = Column(DateTime)
    CandidateTitle = Column(String)
    CandidateFirstName = Column(String)
    CandidateMiddleName = Column(String)
    CandidateLastName = Column(String)
    CandidateBirthDate = Column(Date)
    NoticePeriodID = Column(BigInteger)
    MainDeptID = Column(BigInteger)
    DeptID = Column(BigInteger)
    DesigID = Column(BigInteger)
    CandidateDomainKnowlgID = Column(BigInteger)
    CandidateJobProfileID = Column(BigInteger)
    CandidateGender = Column(String)
    CandidateNationality = Column(String)
    CandidateMaritualStatus = Column(String)
    CandidateIsFresher = Column(Boolean)
    CandidateCorrAdd1 = Column(String)
    CandidateCorrAdd2 = Column(String)
    CandidateCorrAdd3 = Column(String)
    CandidateCorrCityID = Column(BigInteger)
    CandidateCorrPincode = Column(String)
    CandidateCorrStateID = Column(BigInteger)
    CandidateCorrCountryID = Column(BigInteger)
    CandidateCorrPhone1 = Column(String)
    IsVerifiedCandidateCorrPhone1 = Column(Boolean)
    CandidateCorrPhone2 = Column(String)
    IsVerifiedCandidateCorrPhone2 = Column(Boolean)
    CandidatePermAdd1 = Column(String)
    CandidatePermAdd2 = Column(String)
    CandidatePermAdd3 = Column(String)
    CandidatePermCityID = Column(BigInteger)
    CandidatePermPincode = Column(String)
    CandidatePermStateID = Column(BigInteger)
    CandidatePermCountryID = Column(BigInteger)
    CandidatePermPhone1 = Column(String)
    CandidatePermPhone2 = Column(String)
    CandidateEmailID1 = Column(String)
    CandidateEmailID2 = Column(String)
    PANNo = Column(String)
    AadharCardNo = Column(String)
    CandidateTotExperience = Column(Numeric)
    CandidateExpectedCtc = Column(Numeric)
    CandidateRemark = Column(String)
    CandidateLanguageKnown = Column(String)
    CandidateCVFileName = Column(String)
    CandidateCVFileExtention = Column(String)
    CandidatePhotoExtention = Column(String)
    RecruitChannelCategoryID = Column(BigInteger)
    RecruitChannelID = Column(BigInteger)
    RefEmpCompID = Column(BigInteger)
    RefEmpDeptID = Column(BigInteger)
    RefEmpID = Column(BigInteger)
    RefRemark = Column(String)
    CandidateHighestQualificationID = Column(BigInteger)
    ImportInEmployee = Column(Boolean)
    CandidateIsActive = Column(Boolean)
    CandidateIsDeleted = Column(Boolean)
    CandidateCreatedByUserID = Column(BigInteger)
    CandidateEntDt = Column(DateTime)
    CandidateEntUser = Column(String)
    CandidateEntTerm = Column(String)
    CandidateUpdatedByUserID = Column(BigInteger)
    CandidateUpdDt = Column(DateTime)
    CandidateUpdUser = Column(String)
    CandidateUpdTerm = Column(String)
    CandidateDelDt = Column(DateTime)
    CandidateDelUser = Column(String)
    CandidateDelTerm = Column(String)
    CandidateStatusID = Column(BigInteger)
    CandidateMarriageDate = Column(Date)
    CandidateBloodGroupID = Column(BigInteger)
    CastCategoryID = Column(BigInteger)
    ReligionsID = Column(BigInteger)
    MaritualStatusID = Column(BigInteger)
    CandidateAadharCardPhoto = Column(String)
    CandidatePanCardPhoto = Column(String)
    CandidateHaveVoterId = Column(Boolean)
    CandidateVoterIdCardNo = Column(String)
    CandidateVoterCardPhoto = Column(String)
    CandidateHavePassport = Column(Boolean)
    CandidatePassportNo = Column(String)
    CandidatePassportExpiryDate = Column(Date)
    CandidateReligion = Column(BigInteger)
    CandidateCastCategory = Column(BigInteger)
    CandidateHaveDonateBlood = Column(Boolean)
    CandidateDonateBloodTime = Column(BigInteger)
    CandidateHavePhysicallyHandicapped = Column(Boolean)
    CandidateHandicappedCertificateNo = Column(String)
    CandidateHandicappedCertificatePhoto = Column(String)
    CandidateWhyWeHire = Column(String)
    CandidateCorrHouseRent = Column(String)
    CandidateCorrResidingMonth = Column(BigInteger)
    CandidateCorrResidingYear = Column(BigInteger)
    CandidatePermHouseRent = Column(String)
    CandidatePermResidingMonth = Column(BigInteger)
    CandidatePermResidingYear = Column(BigInteger)
    CandidateHaveOwnVechicle = Column(Boolean)
    CandidateHaveDrivingLicense = Column(Boolean)
    CandidateDrivingLicenseNo = Column(String)
    CandidateDrivingLicensePhoto = Column(String)
    CandidateDonateBloodLastDate = Column(Date)
    HandicapCertificateExpiryDate = Column(Date)
    VehicleID = Column(BigInteger)
    CandidateCorrPhone1CodeCountryID = Column(BigInteger)
    CandidatePhotoFileName = Column(String)
    IsAcceptPolicy = Column(Boolean)
    CandidateCorrResidingMonthYear = Column(Date)
    CandidatePermResidingMonthYear = Column(Date)
    CandidateNationalityID = Column(BigInteger)
    CandidateHeight = Column(Numeric)
    CandidateWeight = Column(Numeric)


class RecruitCandidateExperienceDet(MssqlReadBase):
    __tablename__ = "RecruitCandidateExperienceDet"
    __table_args__ = {"schema": "dbo"}

    CandidExpDetID = Column(BigInteger, primary_key=True)
    CandidateID = Column(BigInteger, ForeignKey("dbo.RecruitCandidateMst.CandidateID"))
    PrevOrganizationName = Column(String)
    PrevDurectionFrom = Column(Date)
    PrevDurectionTo = Column(Date)
    PrevDesignation = Column(String)
    PrevCtc = Column(Numeric)
    IsCurrentlyWorking = Column(Boolean)
    CTCTypeID = Column(BigInteger, ForeignKey("dbo.TransactionStatusMst.StatusID"))
    ReasonForChange = Column(String)
    JobResponsibility = Column(String)
    CandidExpIsActive = Column(Boolean)
    CandidExpIsDeleted = Column(Boolean)
    CandidExpEntDt = Column(DateTime)
    CandidExpEntUser = Column(String)
    CandidExpEntTerm = Column(String)
    CandidExpUpdDt = Column(DateTime)
    CandidExpUpdUser = Column(String)
    CandidExpUpdTerm = Column(String)
    CandidExpDelDt = Column(DateTime)
    CandidExpDelUser = Column(String)
    CandidExpDelTerm = Column(String)
    EmploymentType = Column(BigInteger)
    CompanyLocation = Column(String)
    StartMonth = Column(BigInteger)
    StartYear = Column(BigInteger)
    EndMonth = Column(BigInteger)
    EndYear = Column(BigInteger)
    PrevInHandCtc = Column(Numeric)
    StartMonthYear = Column(String)
    EndMonthYear = Column(String)


class RecruitCandidateQualificationDet(MssqlReadBase):
    __tablename__ = "RecruitCandidateQualificationDet"
    __table_args__ = {"schema": "dbo"}

    CandidQualiDetID = Column(BigInteger, primary_key=True)
    CandidateID = Column(BigInteger, ForeignKey("dbo.RecruitCandidateMst.CandidateID"))
    QualificationID = Column(BigInteger, ForeignKey("dbo.QualificationMst.QualificationID"))
    CollegeName = Column(String)
    UniversityName = Column(String)
    PassingYear = Column(BigInteger)
    PassPercentage = Column(Numeric)
    PassGrade = Column(String)
    CandidQualiIsActive = Column(Boolean)
    CandidQualiIsDeleted = Column(Boolean)
    CandidQualiEntDt = Column(DateTime)
    CandidQualiEntUser = Column(String)
    CandidQualiEntTerm = Column(String)
    CandidQualiUpdDt = Column(DateTime)
    CandidQualiUpdUser = Column(String)
    CandidQualiUpdTerm = Column(String)
    CandidQualiDelDt = Column(DateTime)
    CandidQualiDelUser = Column(String)
    CandidQualiDelTerm = Column(String)
    CourseType = Column(BigInteger)
    Pursuing = Column(Boolean)
    FromPassingMonth = Column(BigInteger)
    FromPassingYear = Column(BigInteger)
    ToPassingMonth = Column(BigInteger)
    ToPassingYear = Column(BigInteger)
    UniversityMstID = Column(BigInteger)
    IsOtherUniversity = Column(Boolean)
    UniversityOther = Column(String)
    FromPassingMonthYear = Column(Date)
    ToPassingMonthYear = Column(Date)


class RecruitCandidateSkillDet(MssqlReadBase):
    __tablename__ = "RecruitCandidateSkillDet"
    __table_args__ = {"schema": "dbo"}

    CandidateSkillDetID = Column(BigInteger, primary_key=True)
    CandidateID = Column(BigInteger)
    SkillID = Column(BigInteger)
    IsActive = Column(Boolean)
    EntDt = Column(DateTime)
    EntUser = Column(String)
    EntTerm = Column(String)
    UpdDt = Column(DateTime)
    UpdUser = Column(String)
    UpdTerm = Column(String)


class RecruitCandidateLanguageDet(MssqlReadBase):
    __tablename__ = "RecruitCandidateLanguageDet"
    __table_args__ = {"schema": "dbo"}

    CandidateLanguageDetID = Column(BigInteger, primary_key=True)
    CandidateID = Column(BigInteger, ForeignKey("dbo.RecruitCandidateMst.CandidateID"))
    LanguageID = Column(BigInteger, ForeignKey("dbo.LanguageMst.LanguageID"))
    LanguageRead = Column(Boolean)
    LanguageWrite = Column(Boolean)
    LanguageSpeak = Column(Boolean)
    LanguageIsDeleted = Column(Boolean)
    LanguageEntDt = Column(DateTime)
    LanguageEntUser = Column(String)
    LanguageEntTerm = Column(String)
    LanguageUpdDt = Column(DateTime)
    LanguageUpdUser = Column(String)
    LanguageUpdTerm = Column(String)
    LanguageDelDt = Column(DateTime)
    LanguageDelUser = Column(String)
    LanguageDelTerm = Column(String)
    LanguageIsMother = Column(Boolean)


class RecruitCandidateLocationMst(MssqlReadBase):
    __tablename__ = "RecruitCandidateLocationMst"
    __table_args__ = {"schema": "dbo"}

    CandidateLocationID = Column(BigInteger, primary_key=True)
    CandidateID = Column(BigInteger)
    LocID = Column(BigInteger)
    Latitude = Column(String)
    Longitude = Column(String)
    DistanceInMeter = Column(Integer)
    IsActive = Column(Boolean)
    EntDt = Column(DateTime)
    EntUser = Column(String)
    EntTerm = Column(String)
    UpdDt = Column(DateTime)
    UpdUser = Column(String)
    UpdTerm = Column(String)


class RecruitCandidateNoticePeriodMst(MssqlReadBase):
    __tablename__ = "RecruitCandidateNoticePeriodMst"
    __table_args__ = {"schema": "dbo"}

    NoticePeriodID = Column(BigInteger, primary_key=True)
    NoticePeriod = Column(String)
    NoticePeriodIsActive = Column(Boolean)
    NoticePeriodEntDt = Column(DateTime)
    NoticePeriodEntUser = Column(String)
    NoticePeriodentTerm = Column(String)
    NoticePeriodUpdDt = Column(DateTime)
    NoticePeriodUpdUser = Column(String)
    NoticePeriodUpdTerm = Column(String)
    FlagRuleID = Column(BigInteger)
