-- Privacy-safe LLM execution lineage. Raw prompts, responses, reasoning, and CV content are intentionally excluded.
CREATE TABLE IF NOT EXISTS public.llm_execution_traces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(128) NOT NULL DEFAULT '',
    correlation_id VARCHAR(128) NOT NULL DEFAULT '',
    operation VARCHAR(80) NOT NULL,
    model_identifier_hash VARCHAR(64) NOT NULL,
    model_digest VARCHAR(128) NOT NULL DEFAULT '',
    prompt_version VARCHAR(80) NOT NULL DEFAULT '',
    prompt_hash VARCHAR(64) NOT NULL DEFAULT '',
    source_hash VARCHAR(64) NOT NULL DEFAULT '',
    source_freshness VARCHAR(40) NOT NULL DEFAULT 'unknown',
    input_tokens INTEGER NOT NULL DEFAULT 0,
    output_tokens INTEGER NOT NULL DEFAULT 0,
    duration_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
    inference_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
    validation_ms DOUBLE PRECISION NOT NULL DEFAULT 0,
    attempts INTEGER NOT NULL DEFAULT 0,
    completion_reason VARCHAR(40) NOT NULL DEFAULT '',
    cache_status VARCHAR(20) NOT NULL DEFAULT 'MISS',
    validation_status VARCHAR(40) NOT NULL DEFAULT 'NOT_RUN',
    fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
    error_class VARCHAR(120) NOT NULL DEFAULT '',
    quality_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_llm_execution_traces_request_id ON public.llm_execution_traces (request_id);
CREATE INDEX IF NOT EXISTS ix_llm_execution_traces_correlation_id ON public.llm_execution_traces (correlation_id);
CREATE INDEX IF NOT EXISTS ix_llm_execution_traces_operation ON public.llm_execution_traces (operation);
CREATE INDEX IF NOT EXISTS ix_llm_execution_traces_source_hash ON public.llm_execution_traces (source_hash);
CREATE INDEX IF NOT EXISTS ix_llm_execution_traces_created_at ON public.llm_execution_traces (created_at);
