from typing import Any

DEFAULT_JOB_OPENINGS: list[dict[str, Any]] = [
    {
        "id": "job_frontend_dev",
        "title": "Senior Frontend Developer / React UI Specialist",
        "department": "Engineering",
        "required_skills": [
            "HTML5",
            "CSS3",
            "JavaScript",
            "React",
            "Tailwind CSS",
            "Bootstrap",
            "Figma",
            "Git",
        ],
        "preferred_keywords": [
            "Figma to Code",
            "UI Components",
            "Shopify",
            "Responsive Design",
            "Material UI",
            "REST API",
            "TypeScript",
            "Elementor",
        ],
    },
    {
        "id": "job_backend_dev",
        "title": "Backend Engineer / Python & Node.js Developer",
        "department": "Engineering",
        "required_skills": [
            "Python",
            "FastAPI",
            "Node.js",
            "Express.js",
            "MongoDB",
            "SQL",
            "REST API",
            "Git",
        ],
        "preferred_keywords": [
            "JWT",
            "Microservices",
            "PostgreSQL",
            "Docker",
            "Asyncio",
            "Nodemailer",
            "CRUD",
            "Unit Testing",
        ],
    },
    {
        "id": "job_fullstack_dev",
        "title": "Full Stack Software Engineer",
        "department": "Engineering",
        "required_skills": [
            "JavaScript",
            "Python",
            "React",
            "Node.js",
            "HTML5",
            "CSS3",
            "SQL",
            "MongoDB",
            "Git",
        ],
        "preferred_keywords": [
            "REST API",
            "Docker",
            "FastAPI",
            "EJS",
            "Bootstrap",
            "Tailwind",
            "Agile",
            "CI/CD",
        ],
    },
    {
        "id": "job_ui_ux_designer",
        "title": "UI/UX & Product Designer",
        "department": "Design & Product",
        "required_skills": [
            "Figma",
            "Adobe Photoshop",
            "Adobe XD",
            "Wireframing",
            "UI/UX Design",
            "Dashboard Design",
            "Design Systems",
        ],
        "preferred_keywords": [
            "Prototyping",
            "User Experience",
            "User Interface",
            "Landing Page",
            "Web Design",
            "Visual Design",
            "Canva",
        ],
    },
    {
        "id": "job_shopify_developer",
        "title": "E-Commerce & Shopify Liquid Developer",
        "department": "E-Commerce",
        "required_skills": [
            "Shopify",
            "Shopify Liquid",
            "HTML5",
            "CSS3",
            "JavaScript",
            "Theme Customization",
        ],
        "preferred_keywords": [
            "Custom Sections",
            "Figma to Shopify",
            "E-Commerce",
            "Liquid Templates",
            "Responsive Web",
        ],
    },
]
